export CLICOLOR=1
export LS_OPTIONS='--color=auto'
export LSCOLORS='ExGxFxdaCxDaDahbadacex'
export HISTTIMEFORMAT='%F %T '
export HISTFILE="$HOME/.zsh_history"
export HISTSIZE=10000000
export SAVEHIST=10000000

export HOMEBREW_NO_AUTO_UPDATE=true
export GOPATH="$HOME/Project/Go"
export GOPROXY=https://goproxy.cn

# ruby
export SDKROOT=$(xcrun --show-sdk-path)
export PATH="/usr/local/opt/ruby/bin:/usr/local/lib/ruby/gems/3.0.0/bin:$PATH"
export PATH="$HOME/.gem/ruby/3.0.0/bin:$PATH"


alias ll="ls -al"
alias OS="neofetch"
alias brew-uuc="brew update && brew upgrade && brew cleanup"
alias brew-delete="rm ~/Library/Caches/Homebrew/downloads/*"
alias unrar="unrar x"
alias rar="rar a"
alias 7z="7zz e"
alias 'rm -rf'="rm"
alias uppic="picgo upload"
alias picls="cat .picgo/picgo.log"
alias Typora="/Applications/Typora.app/Contents/MacOS/Typora"

#python
python3="/usr/local/bin/python3"
alias python="python3"
#pip
alias pip="pip3"
#jupyter
alias notebook="jupyter-notebook"

#zsh
source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/local/opt/zsh-fast-syntax-highlighting/share/zsh-fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh
source /usr/local/share/zsh-incr/incr-0.2.zsh


autoload -U colors && colors
PS1="%{$fg_bold[green]%}➜%{$reset_color%} %{$fg[cyan]%}%~ "
RPROMPT="%F{23}[%*]%f"


alias aliyun='ssh -N -f -L localhost:1234:localhost:1234 aeiou@112.74.108.206'


alias rm=del        #使用别名del代替rm
del()               #函数del，作用：将rm命令修改为mv命令
{
  mv $@ ~/.Trash
}

